# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.5.4"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.4/netbird_0.5.4_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6c914ba8ba0c9c80a4b1e1cae0b8b72956e8172d84b90bf618d3f737ff287a7c"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.4/netbird_0.5.4_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f7a760a8dcca45bc7c5a7e8e7e7c65e063e4de9421a0926b2e9d0a1f5a0fc29c"

      def install
        bin.install "netbird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.4/netbird_0.5.4_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "74345c15737d5b45adccb8c9d0b776a85dfd05de9cf40ec11c9db848fbe6786e"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.4/netbird_0.5.4_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ceadb7082237a4c99cccd8fe19e37b4edd4b5cc8d6ba0683020ef0bc956d0013"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.4/netbird_0.5.4_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "64ddfa192471db90f40861384e2f1856abd9da3a1c8db7486ea6da8109136f79"

      def install
        bin.install "netbird"
      end
    end
  end

  test do
    system "#{bin}/netbird -h"
  end
end
