# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netbird < Formula
  desc "Netbird project."
  homepage "https://netbird.io/"
  version "0.5.9"
  license "BSD3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.9/netbird_0.5.9_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f6f259f0c029d4685f6afa270817280677150d2955177c7079261b353365aa66"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.9/netbird_0.5.9_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "d25e9b60f536ebd8d5c66c67ebaec46e982dc795f94e4d92715b3efa524a8aff"

      def install
        bin.install "netbird"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.9/netbird_0.5.9_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "a3ecd10f2a8c07e840144b5a0de0523abe8f11e39712751005e8dfcbab045502"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.9/netbird_0.5.9_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b1d43c2452ecdfbbfffd317ca4b6c56ad15b4d599962e3d513e9c3172e8c9796"

      def install
        bin.install "netbird"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mlsmaycon/netbird/releases/download/v0.5.9/netbird_0.5.9_linux_armv6.tar.gz", :using => CurlDownloadStrategy
      sha256 "a86de0b6b3e670534de319bb19f05dfdb74e6fa3037cba084226ac93fa1b3fd7"

      def install
        bin.install "netbird"
      end
    end
  end

  test do
    system "#{bin}/netbird -h"
  end
end
